### ISSUE TITLE
For  "region-cloner " add a progress bar.

### ISSUE THREAD

**Issue by flameSla** [mulark/factorio_benchmarking_mods#2]
With a large amount of copying, it is unclear whether Factorio is frozen or continues to work. I suggest adding a progress bar.

The progress bar should be enabled in the settings, it is disabled by default.

The progress bar displays text messages to the console: "1 out of 1000 copies has been completed"

**Comment by mulark** [comment]
All clones are performed in the same tick so printing to the console wouldn't be effective. However we could potentially log to factorio-current.log during the clone.
