### ISSUE TITLE
Region cloner placed overlapping beacons

### ISSUE THREAD

**Issue by rpdelaney** [mulark/factorio_benchmarking_mods#5]
![74137251 475_image](https://user-images.githubusercontent.com/1139517/151668569-89e041bf-ee9d-4ca1-a628-ec97ba890ac7.png)

When cloning an area with beacons onto an area that already had some beacons placed, region cloner placed overlapping beacons on some map tiles, which resulted in inaccurate benchmarks:

![OhNoBenchmarking](https://user-images.githubusercontent.com/1139517/151668422-d5714f5f-b888-4f89-8d9b-4b0ab4d055bd.png)

**Comment by mulark** [comment]
So, some considerations here. If clear paste area is not checked, it is easy to end up overlapping entities. But that is likely not the main issue at hand. Even when it is checked, there is some effort to not clear entities that are a member of the source entity listing. (I forget what exactly the specifics were but recall something about addressing edge cases when the source area is smaller than the area the area the entities being cloned inhabit (like if a rocket silo was cloned from a 1x1 source area)).

What I have been doing to clone beaconed builds with sharing is to manually ignore one row of beacons (ex: top row in your example). Thus selecting the bottom 10 rows of the example build. This would allow cloning in the south direction while maintaining proper sharing and no-overlapping entities.

**Comment by rpdelaney** [comment]
[Known issues](https://github.com/mulark/factorio_benchmarking_mods/blob/master/region-cloner/doc/Documentation.md#known-issues) maybe?

**Comment by B3lt3r** [comment]
OK this was reported by me in factorio forums...

Yes, with smart selection it is easy to use region cloner lesson learned... just don't overlap, period :) My issues are:
- it happens in advanced mode both if clear paste area is set or not
- hard to detect and justify why it works this way. NOW I know that I can see the shadows and also can use copy region which counts the beacons properly
- using advanced settings I can put any # of beacons (or assembling machines) on top of each other



![image](https://user-images.githubusercontent.com/86040558/152433593-050a922c-edad-4972-8916-aa312d0b26c8.png)
![image](https://user-images.githubusercontent.com/86040558/152433622-7fa1e541-9581-4d49-a5d5-f982c127c731.png)
![image](https://user-images.githubusercontent.com/86040558/152433659-c044ce38-b1b1-4bc7-8bb9-9d33aaea877b.png)

**Comment by mulark** [comment]
I recalled why I made it so that overlapping clones do not destroy the source entities. It's because when cloning more than one paste, if the first paste destroys the source entity, cloning the next paste will not have all source entities as valid to copy from. 

One idea about this, is to add the source entities as "scheduled to be destroyed". Once all clones have been done, destroy them. This should fix the issue where more overlapping entities can pile up.

**Comment by mulark** [comment]
Thanks for the reports, this should be resolved via https://github.com/mulark/factorio_benchmarking_mods/commit/fdb29b80f82bb931659952a8a0d7f05a9cfb2a20 (and updated on mod portal).

Note that for very large pastes, it will still be more performant to not overlap the beacons when cloning.

**Comment by B3lt3r** [comment]
I really appreciate your support. Now I cannot create those magical structures if "clear paste area" is on, just tested. 
TY!

**Comment by rpdelaney** [comment]
Sounds like this can be closed?
